In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
file_path = '/content/drive/MyDrive/book_recommendation/book_recommendation/books_cleaned.csv'
print(f"File path constructed: {file_path}")

File path constructed: /content/drive/MyDrive/book_recommendation/book_recommendation/books_cleaned.csv

In [5]:
import pandas as pd
books = pd.read_csv(file_path)
print("Books DataFrame loaded successfully.")
books.head()

Books DataFrame loaded successfully.

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead:,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web:A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels:,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves:,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain:,"9780006280934 ""In The Problem of Pain, C.S. Le..."

In [6]:
pip install python-dotenv

Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (1.2.2)

In [7]:
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Verify if HF_TOKEN is loaded
if 'HF_TOKEN' in os.environ:
    print("HF_TOKEN successfully loaded from .env file.")
else:
    print("HF_TOKEN not found in environment variables after loading .env. Please ensure your .env file is in the correct directory and contains HF_TOKEN.")

HF_TOKEN not found in environment variables after loading .env. Please ensure your .env file is in the correct directory and contains HF_TOKEN.

In [8]:
from transformers import pipeline
classifier = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      top_k = None,
                      device = 0)
classifier("I love this!")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/329M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: j-hartmann/emotion-english-distilroberta-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/294 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/329M [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.00852868054062128},
  {'label': 'neutral', 'score': 0.005764591973274946},
  {'label': 'anger', 'score': 0.004419785924255848},
  {'label': 'sadness', 'score': 0.0020923891570419073},
  {'label': 'disgust', 'score': 0.001611991785466671},
  {'label': 'fear', 'score': 0.00041385178337804973}]]

In [9]:

books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [10]:

classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.6548413634300232},
  {'label': 'neutral', 'score': 0.16985207796096802},
  {'label': 'sadness', 'score': 0.11640888452529907},
  {'label': 'surprise', 'score': 0.02070062793791294},
  {'label': 'disgust', 'score': 0.019100705161690712},
  {'label': 'joy', 'score': 0.015161297284066677},
  {'label': 'anger', 'score': 0.003935146611183882}]]

In [11]:
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.7296026945114136},
  {'label': 'neutral', 'score': 0.1403856873512268},
  {'label': 'fear', 'score': 0.06816219538450241},
  {'label': 'joy', 'score': 0.04794241115450859},
  {'label': 'anger', 'score': 0.009156348183751106},
  {'label': 'disgust', 'score': 0.00262847519479692},
  {'label': 'sadness', 'score': 0.0021221605129539967}],
 [{'label': 'neutral', 'score': 0.44937071204185486},
  {'label': 'disgust', 'score': 0.2735914885997772},
  {'label': 'joy', 'score': 0.10908304899930954},
  {'label': 'sadness', 'score': 0.09362724423408508},
  {'label': 'anger', 'score': 0.040478333830833435},
  {'label': 'surprise', 'score': 0.02697017975151539},
  {'label': 'fear', 'score': 0.006879060063511133}],
 [{'label': 'neutral', 'score': 0.6462162137031555},
  {'label': 'sadness', 'score': 0.2427332103252411},
  {'label': 'disgust', 'score': 0.04342261329293251},
  {'label': 'surprise', 'score': 0.028300540521740913},
  {'label': 'joy', 'score': 0.014211442321538925},
  {'label': 'fear', 'score': 0.014084079302847385},
  {'label': 'anger', 'score': 0.01103188470005989}],
 [{'label': 'fear', 'score': 0.928167998790741},
  {'label': 'anger', 'score': 0.03219102695584297},
  {'label': 'neutral', 'score': 0.012808729894459248},
  {'label': 'sadness', 'score': 0.008756889030337334},
  {'label': 'surprise', 'score': 0.008597911335527897},
  {'label': 'disgust', 'score': 0.008431846275925636},
  {'label': 'joy', 'score': 0.001045582932420075}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104170888662338},
  {'label': 'disgust', 'score': 0.006480592768639326},
  {'label': 'fear', 'score': 0.005393994972109795},
  {'label': 'surprise', 'score': 0.0022869433742016554},
  {'label': 'anger', 'score': 0.0018428893527016044},
  {'label': 'joy', 'score': 0.0017338789766654372}],
 [{'label': 'joy', 'score': 0.9327971935272217},
  {'label': 'disgust', 'score': 0.03771771863102913},
  {'label': 'neutral', 'score': 0.01589190773665905},
  {'label': 'sadness', 'score': 0.006444551516324282},
  {'label': 'anger', 'score': 0.005025018472224474},
  {'label': 'surprise', 'score': 0.0015812073834240437},
  {'label': 'fear', 'score': 0.0005423100665211678}],
 [{'label': 'joy', 'score': 0.6528703570365906},
  {'label': 'neutral', 'score': 0.25427502393722534},
  {'label': 'surprise', 'score': 0.0680830255150795},
  {'label': 'sadness', 'score': 0.009908979758620262},
  {'label': 'disgust', 'score': 0.006512209307402372},
  {'label': 'anger', 'score': 0.00482131028547883},
  {'label': 'fear', 'score': 0.0035290152300149202}],
 [{'label': 'neutral', 'score': 0.5494765639305115},
  {'label': 'sadness', 'score': 0.1116902083158493},
  {'label': 'disgust', 'score': 0.10400670021772385},
  {'label': 'surprise', 'score': 0.07876556366682053},
  {'label': 'anger', 'score': 0.0641336739063263},
  {'label': 'fear', 'score': 0.05136282742023468},
  {'label': 'joy', 'score': 0.040564440190792084}]]

In [12]:

sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [13]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [14]:

predictions[0]

[{'label': 'surprise', 'score': 0.7296026945114136},
 {'label': 'neutral', 'score': 0.1403856873512268},
 {'label': 'fear', 'score': 0.06816219538450241},
 {'label': 'joy', 'score': 0.04794241115450859},
 {'label': 'anger', 'score': 0.009156348183751106},
 {'label': 'disgust', 'score': 0.00262847519479692},
 {'label': 'sadness', 'score': 0.0021221605129539967}]

In [15]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [16]:

predictions[3]

[{'label': 'fear', 'score': 0.928167998790741},
 {'label': 'anger', 'score': 0.03219102695584297},
 {'label': 'neutral', 'score': 0.012808729894459248},
 {'label': 'sadness', 'score': 0.008756889030337334},
 {'label': 'surprise', 'score': 0.008597911335527897},
 {'label': 'disgust', 'score': 0.008431846275925636},
 {'label': 'joy', 'score': 0.001045582932420075}]

In [17]:
predictions

[[{'label': 'surprise', 'score': 0.7296026945114136},
  {'label': 'neutral', 'score': 0.1403856873512268},
  {'label': 'fear', 'score': 0.06816219538450241},
  {'label': 'joy', 'score': 0.04794241115450859},
  {'label': 'anger', 'score': 0.009156348183751106},
  {'label': 'disgust', 'score': 0.00262847519479692},
  {'label': 'sadness', 'score': 0.0021221605129539967}],
 [{'label': 'neutral', 'score': 0.44937071204185486},
  {'label': 'disgust', 'score': 0.2735914885997772},
  {'label': 'joy', 'score': 0.10908304899930954},
  {'label': 'sadness', 'score': 0.09362724423408508},
  {'label': 'anger', 'score': 0.040478333830833435},
  {'label': 'surprise', 'score': 0.02697017975151539},
  {'label': 'fear', 'score': 0.006879060063511133}],
 [{'label': 'neutral', 'score': 0.6462162137031555},
  {'label': 'sadness', 'score': 0.2427332103252411},
  {'label': 'disgust', 'score': 0.04342261329293251},
  {'label': 'surprise', 'score': 0.028300540521740913},
  {'label': 'joy', 'score': 0.014211442321538925},
  {'label': 'fear', 'score': 0.014084079302847385},
  {'label': 'anger', 'score': 0.01103188470005989}],
 [{'label': 'fear', 'score': 0.928167998790741},
  {'label': 'anger', 'score': 0.03219102695584297},
  {'label': 'neutral', 'score': 0.012808729894459248},
  {'label': 'sadness', 'score': 0.008756889030337334},
  {'label': 'surprise', 'score': 0.008597911335527897},
  {'label': 'disgust', 'score': 0.008431846275925636},
  {'label': 'joy', 'score': 0.001045582932420075}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104170888662338},
  {'label': 'disgust', 'score': 0.006480592768639326},
  {'label': 'fear', 'score': 0.005393994972109795},
  {'label': 'surprise', 'score': 0.0022869433742016554},
  {'label': 'anger', 'score': 0.0018428893527016044},
  {'label': 'joy', 'score': 0.0017338789766654372}],
 [{'label': 'joy', 'score': 0.9327971935272217},
  {'label': 'disgust', 'score': 0.03771771863102913},
  {'label': 'neutral', 'score': 0.01589190773665905},
  {'label': 'sadness', 'score': 0.006444551516324282},
  {'label': 'anger', 'score': 0.005025018472224474},
  {'label': 'surprise', 'score': 0.0015812073834240437},
  {'label': 'fear', 'score': 0.0005423100665211678}],
 [{'label': 'joy', 'score': 0.6528703570365906},
  {'label': 'neutral', 'score': 0.25427502393722534},
  {'label': 'surprise', 'score': 0.0680830255150795},
  {'label': 'sadness', 'score': 0.009908979758620262},
  {'label': 'disgust', 'score': 0.006512209307402372},
  {'label': 'anger', 'score': 0.00482131028547883},
  {'label': 'fear', 'score': 0.0035290152300149202}],
 [{'label': 'neutral', 'score': 0.5494765639305115},
  {'label': 'sadness', 'score': 0.1116902083158493},
  {'label': 'disgust', 'score': 0.10400670021772385},
  {'label': 'surprise', 'score': 0.07876556366682053},
  {'label': 'anger', 'score': 0.0641336739063263},
  {'label': 'fear', 'score': 0.05136282742023468},
  {'label': 'joy', 'score': 0.040564440190792084}]]

In [18]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.009156348183751106},
 {'label': 'disgust', 'score': 0.00262847519479692},
 {'label': 'fear', 'score': 0.06816219538450241},
 {'label': 'joy', 'score': 0.04794241115450859},
 {'label': 'neutral', 'score': 0.1403856873512268},
 {'label': 'sadness', 'score': 0.0021221605129539967},
 {'label': 'surprise', 'score': 0.7296026945114136}]

In [19]:
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [20]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [21]:
emotion_scores

{'anger': [np.float64(0.0641336739063263),
  np.float64(0.6126185059547424),
  np.float64(0.0641336739063263),
  np.float64(0.35148391127586365),
  np.float64(0.08141247183084488),
  np.float64(0.2322249710559845),
  np.float64(0.5381842255592346),
  np.float64(0.0641336739063263),
  np.float64(0.30067017674446106),
  np.float64(0.0641336739063263)],
 'disgust': [np.float64(0.2735914885997772),
  np.float64(0.3482844829559326),
  np.float64(0.10400670021772385),
  np.float64(0.15072263777256012),
  np.float64(0.1844954937696457),
  np.float64(0.727174699306488),
  np.float64(0.15585491061210632),
  np.float64(0.10400670021772385),
  np.float64(0.2794813811779022),
  np.float64(0.1779276728630066)],
 'fear': [np.float64(0.928167998790741),
  np.float64(0.9425278306007385),
  np.float64(0.9723208546638489),
  np.float64(0.36070623993873596),
  np.float64(0.09504325687885284),
  np.float64(0.05136282742023468),
  np.float64(0.7474286556243896),
  np.float64(0.4044959247112274),
  np.float64(0.9155241250991821),
  np.float64(0.05136282742023468)],
 'joy': [np.float64(0.9327971935272217),
  np.float64(0.7044215202331543),
  np.float64(0.7672368884086609),
  np.float64(0.25188079476356506),
  np.float64(0.040564440190792084),
  np.float64(0.04337584972381592),
  np.float64(0.8725654482841492),
  np.float64(0.040564440190792084),
  np.float64(0.040564440190792084),
  np.float64(0.040564440190792084)],
 'sadness': [np.float64(0.6462162137031555),
  np.float64(0.887939453125),
  np.float64(0.5494765639305115),
  np.float64(0.732685387134552),
  np.float64(0.8843895196914673),
  np.float64(0.6213927268981934),
  np.float64(0.7121942639350891),
  np.float64(0.5494765639305115),
  np.float64(0.8402896523475647),
  np.float64(0.8603722453117371)],
 'surprise': [np.float64(0.9671575427055359),
  np.float64(0.1116902083158493),
  np.float64(0.1116902083158493),
  np.float64(0.1116902083158493),
  np.float64(0.4758807122707367),
  np.float64(0.1116902083158493),
  np.float64(0.40800026059150696),
  np.float64(0.820281982421875),
  np.float64(0.35446029901504517),
  np.float64(0.1116902083158493)],
 'neutral': [np.float64(0.7296026945114136),
  np.float64(0.2525450885295868),
  np.float64(0.07876556366682053),
  np.float64(0.07876556366682053),
  np.float64(0.07876556366682053),
  np.float64(0.27190276980400085),
  np.float64(0.07876556366682053),
  np.float64(0.23448744416236877),
  np.float64(0.13561409711837769),
  np.float64(0.07876556366682053)]}

In [22]:
from tqdm import tqdm

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5197/5197 [02:44<00:00, 31.56it/s]

In [23]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [24]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273591,0.928168,0.932797,0.646216,0.967158,0.729603,9780002005883
1,0.612619,0.348284,0.942528,0.704422,0.887939,0.111690,0.252545,9780002261982
2,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078766,9780006178736
3,0.351484,0.150723,0.360706,0.251881,0.732685,0.111690,0.078766,9780006280897
4,0.081412,0.184495,0.095043,0.040564,0.884390,0.475881,0.078766,9780006280934
...,...,...,...,...,...,...,...,...
5192,0.148208,0.030643,0.919165,0.255170,0.853722,0.980877,0.030656,9788172235222
5193,0.064134,0.114383,0.051363,0.400263,0.883199,0.111690,0.227765,9788173031014
5194,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625,9788179921623
5195,0.064134,0.104007,0.459269,0.759455,0.951104,0.368111,0.078766,9788185300535
5196,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078766,9789027712059

In [25]:
books = pd.merge(books, emotions_df, on = "isbn13")

In [26]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead:,9780002005883 A NOVEL THAT READERS and critics...,0.064134,0.273591,0.928168,0.932797,0.646216,0.967158,0.729603
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web:A Novel,9780002261982 A new 'Christie for Christmas' -...,0.612619,0.348284,0.942528,0.704422,0.887939,0.111690,0.252545
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels:,"9780006178736 A memorable, mesmerizing heroine...",0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078766
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves:,9780006280897 Lewis' work on the nature of lov...,0.351484,0.150723,0.360706,0.251881,0.732685,0.111690,0.078766
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain:,"9780006280934 ""In The Problem of Pain, C.S. Le...",0.081412,0.184495,0.095043,0.040564,0.884390,0.475881,0.078766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity:,9788172235222 On A Train Journey Home To North...,0.148208,0.030643,0.919165,0.255170,0.853722,0.980877,0.030656
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East:,9788173031014 This book tells the tale of a ma...,0.064134,0.114383,0.051363,0.400263,0.883199,0.111690,0.227765
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that:Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,0.064134,0.104007,0.459269,0.759455,0.951104,0.368111,0.078766
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology:,9789027712059 Since the three volume edition o...,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078766

In [27]:
books.to_csv("books_with_emotions.csv", index = False)

In [31]:
books.to_csv("/content/drive/MyDrive/book_recommendation/book_recommendation/books_with_emotions.csv", index = False)